#ifndef DEFINTIONS_H
#define DEFINITIONS_H

#define SCREEN_WIDTH GAMERENDER_H::SCREEN_W
#define SCREEN_HEIGHT GAMERENDER_::SCREEN_H
#define CARD_WIDTH CARD_H::WIDTH
#define CARD_HEIGHT CARD_H::HEIGHT

#endif // !1
